### ISSUE TITLE
Error while importing State of the Union dataset

### ISSUE THREAD

**Issue by cojoco** [BYU-NLP-Lab/topicalguide#65]
All of this is being done on the Dev branch, freshly forked from the BYU-NLP-Lab repo.
Whenever I attempt to import the State of the Union dataset, I get the following error:

Traceback (most recent call last):
  File "tg.py", line 452, in <module>
    main()
  File "tg.py", line 446, in main
    execute[args.which](args)
  File "tg.py", line 82, in exec_import_dataset
    dataset = get_dataset(args)
  File "tg.py", line 53, in get_dataset
    dataset = datasets[args.dataset_class](args.dataset, is_recursive=args.recursive)
  File "/home/connor/git/cojoco/topicalguide/import_tool/dataset/interfaces/generic_dataset.py", line 45, in __init__
    settings = json.loads(raw_text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 33 column 1 (char 1138)

It throws the following exception at the end of the output from the import attempt: "Exception: No documents to perform analysis on."

I looked around a bit online, and it appears that this commonly occurs whenever the input to json.loads() is accidentally surrounded by single quotes rather than double quotes.

**Comment by ringger** [comment]
Thank you for this report, cojoco.

 

Ethan Garofolo will be able to follow up with you directly about this problem.

 

--Eric

**Comment by juanpaco** [comment]
@cojoco - It looks like there was a rogue comma in the settings file for the State of the Union dataset.  I've checked in a fix for that file.

Would you mind pulling the latest `dev` branch and trying again?

**Comment by juanpaco** [comment]
I'm also going to mark this closed.  If that fix hasn't resolved the issue, please re-open this ticket.
