### ISSUE TITLE
2D Plot Y-axis shows as 'Metadata: undefined' after selecting a topic

### ISSUE THREAD

**Issue by cojoco** [BYU-NLP-Lab/topicalguide#74]
I select the State of the Union dataset, then select a topic. I then click 'Visualizations' and select '2D Plots'. It shows the Y-axis in the controls as the topic I picked, but shows the Y-axis on the graph as 'Metadata: undefined' and shows no data. It shows data and titles the axis correctly if you change the Y-axis in the controls, and you can change it back to the topic you started with and it will then work correctly.

This is on the dev branch, cloned from https://github.com/cojoco/topicalguide/tree/dev

**Comment by juanpaco** [comment]
Madison said she'd look into this.

**Comment by madisonjbrooks12** [comment]
Finally fixed this bug. The y-axis group was automatically being set to "Metadata" and needed to be set to "Topics."
