### ISSUE TITLE
Error from "Import_state_of_the_union.sh":  WindowsError [Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Eupraxis** [BYU-NLP-Lab/topicalguide#75]
I have a Windows 7 PC on a 64-bit architecture. I am running Python 2.7 (32 bit). I ran the installation steps from the Git Bash console (hence the un-Windows looking prompts). All steps completed fine except for compiling the stemmer, which thew the following exception:

![stemmer error](https://cloud.githubusercontent.com/assets/13827443/9443797/2eb6a94e-4a51-11e5-9d0f-19e2ee62611b.PNG)

Since it appeared that it created the stemmer anyway, I went ahead with the rest of the configuration, including setting up Django secret key, setting debug to true. I then ran the import shell script. All seemed to be going OK (lots of output information), but then it ground to halt with the following error:

![error](https://cloud.githubusercontent.com/assets/13827443/9443837/644039c2-4a51-11e5-9047-83fe8cb972f5.PNG)

What is going on here? (BTW: I get the same error if I do the above from the windows command prompt, so it doesn't appear to be due to Git Bash or Mingw32).

**Comment by cojoco** [comment]
Hello Eupraxis,

The problem is likely caused by the C files that are used to build Snowball. Snowball was made to work in Unix-like systems, and it may not work with Windows.

I'm not sure if this will work, but since it does look like it built something, one thing you could try is opening ~/topicalguide/import_tool/analysis/stemmer.py and changing the "self.stemmer_path" to "abspath(join(topical_guide_root_dir, 'tools/stemmer/stemmer.exe'))". It looks like right now it is missing the '.exe' (since it is meant to work with Unix-like systems, and we haven't tried it with Windows), so stemmer.py may be pointing at the wrong executable for Windows machines.

Try that out, and let us know if it works.

Thanks for your report!

-Connor

**Comment by Eupraxis** [comment]
Hi Connor:

That worked as far as getting the stemmer to compile. However, you actually
need to modify two files: The shell script (make_english_stemmer.sh)  and
the stemmer.py, as both make Unix-like calls (the firmer to "./Snowball"
instead of "./Snowball.exe", the latter to "/stemmer" like you pointed out).

However, I am still getting the above error when I try to import the state
of the union speeches. I've traced the error to a command call to Mallet in
mallet_analysis.py [line 326): The list assigned to cmd is equal to:

cmd=[u'c:\\Users\\Mike\\topicalguide\\tools/mallet/mallet', u'import-file',
u'--input',
u'c:\\Users\\Mike\\topicalguide\\working\\datasets\\state_of_the_union\\analyses\\lda100topics\\mallet_input.txt',
u'--output',
u'c:\\Users\\Mike\\topicalguide\\working\\datasets\\state_of_the_union\\analyses\\lda100topics\\imported_data.mallet',
u'--token-regex', u'[\\S]+', u'--keep-sequence', u'--set-source-by-name',
u'--remove-stopwords']

I saw nothing wrong with this, but I decided to looko at the file
referenced by the first list element:
c:\\Users\\Mike\\topicalguide\\tools/mallet/mallet

This is the mallet configuration file that sets up the analysis. It's
totally "Unixed" with $ all over the place.

My guess, based on the error referring to a "%1" being called, is that the
error may be here:

*run) CLASS=$1; shift;;*

Within the mallet file.

Anyway, that's as far as I can get. I am assuming Mallet itself if OK since
its on a Java platform, so its really just calls to Windows to get Java up
and running.

Mike

**Comment by cojoco** [comment]
Hi again Mike,

It sounds like that's very likely the culprit (possibly one of many), but unfortunately we don't have enough time to focus on getting the Topical Guide working with Windows right now. It is very possible that we will work on it in the future, and what you've found so far will no doubt be very valuable when that time comes. You would probably have better luck using Linux (we're using Fedora 22 right now), and if you're still interested in working with the Topical Guide I would suggest getting a Linux virtual machine running on your machine.

Thank you for your interest, and your contribution to the project!

-Connor

**Comment by Eupraxis** [comment]
Fair enough. We're probably going to deploy it on a linux server anyway, so
its more of a prototyping inconvenience. Ill look into getting Linux vm.

**Comment by juanpaco** [comment]
@Eupraxis No idea how much you've looked into this in the past, but here are a few options (I'm assuming you're on Windows):

* [Microsoft's VirtualPC](http://www.microsoft.com/windows/virtual-pc/) - (free) - I've never used this one
* [virtualbox](https://www.virtualbox.org/wiki/Downloads) - (free) - is a good solution there if you're looking for the low-cost route.
* [VMWare](http://www.vmware.com/products/player/) - (free for personal use) - http://www.vmware.com/products/player/  I've used VMWare stuff a lot and like it.

**Comment by juanpaco** [comment]
Also, @cojoco is right in that we don't have the bandwidth to figure out Windows.  :(  If you do pursue that option further and figure it out, we'd be happy to add Windows support instructions though.

**Comment by Eupraxis** [comment]
Thanks Ethan. I have virtual box since I uses SAGE CAS. Ill stick with that
:-) I appreciate all your efforts at making this open source product
available. Totally understand that we all have day jobs ;-)
