### ISSUE TITLE
Django error when importing dataset

### ISSUE THREAD

**Issue by madisonjbrooks12** [BYU-NLP-Lab/topicalguide#86]
Me again. It no longer freezes when I import a dataset, but now I get the following error:

    django.db.utils.OperationalError: no such column: visualize_metadatatype.dataset_id

Researching this error made me think that this has to do with fixing the model of the database itself somehow, so I don't think this is something I can (or should) fix on my own. In other words, I don't think this can be fixed with installing a new package. But maybe I just need to install the latest version of django. I'm just tentative to mess with it at this point.

I am able to run the server even with this error, but the page just tells me that there is an error somewhere, so I need to get this fixed in order to run the Topical Guide.

**Comment by juanpaco** [comment]
Did you re-run the migrations once you switched over to the dev branch?

**Comment by madisonjbrooks12** [comment]
Sorry for my ignorance, but how do you do that?

**Comment by juanpaco** [comment]
No apologies needed.  I thought it was in the README, but it isn't.

`python manage.py migrate` is the command.

**Comment by madisonjbrooks12** [comment]
I successfully re-ran the migrations, but the same error comes up.
